import { Restaurant } from "@/types";

export const restaurants: Restaurant[] = [
    {
        id: "r1",
        name: "비스트로에버",
        category: "양식",
        address: "서울 마포구 매봉산로 75",
        rating: 4.5,
        reviewCount: 120,
        imageUrl: "https://placehold.co/400x300/FF6B6B/FFFFFF?text=BistroEver",
        link: "https://map.naver.com"
    },
    {
        id: "r2",
        name: "크라이치즈버거 상암",
        category: "버거",
        address: "서울 마포구 매봉산로 75",
        rating: 4.8,
        reviewCount: 350,
        imageUrl: "https://placehold.co/400x300/FFA500/FFFFFF?text=CryCheese",
    },
    {
        id: "r3",
        name: "피제리아 스너그",
        category: "양식",
        address: "서울 마포구 매봉산로 75",
        rating: 4.7,
        reviewCount: 89,
        imageUrl: "https://placehold.co/400x300/FF6347/FFFFFF?text=Snug",
    },
    {
        id: "r4",
        name: "더브래드팬트리",
        category: "베이커리/카페",
        address: "서울 마포구 매봉산로 75",
        rating: 4.6,
        reviewCount: 200,
        imageUrl: "https://placehold.co/400x300/8B4513/FFFFFF?text=BreadPantry",
    },
    {
        id: "r5",
        name: "늘푸른목장",
        category: "한식/고기",
        address: "서울 마포구 매봉산로2길 15",
        rating: 4.4,
        reviewCount: 150,
        imageUrl: "https://placehold.co/400x300/A52A2A/FFFFFF?text=Mokjang",
    },
    {
        id: "r6",
        name: "음 세이로무시",
        category: "일식",
        address: "서울 마포구 매봉산로2길 15",
        rating: 4.5,
        reviewCount: 90,
        imageUrl: "https://placehold.co/400x300/4682B4/FFFFFF?text=Seiromushi",
    },
    {
        id: "r7",
        name: "정통집 상암점",
        category: "한식",
        address: "서울 마포구 매봉산로2길 15",
        rating: 4.3,
        reviewCount: 300,
        imageUrl: "https://placehold.co/400x300/CD5C5C/FFFFFF?text=Jeongtong",
    },
    {
        id: "r8",
        name: "꼬닭",
        category: "한식/닭요리",
        address: "서울 마포구 월드컵북로",
        rating: 4.2,
        reviewCount: 50,
        imageUrl: "https://placehold.co/400x300/FFD700/FFFFFF?text=Kkodak",
    },
    {
        id: "r9",
        name: "골목대장 포장마차",
        category: "해산물/술집",
        address: "서울 마포구 상암동",
        rating: 4.0,
        reviewCount: 40,
        imageUrl: "https://placehold.co/400x300/000080/FFFFFF?text=Golmok",
    },
    {
        id: "r10",
        name: "배꼽집 상암점",
        category: "한식/냉면",
        address: "서울 마포구 월드컵북로 54길",
        rating: 4.4,
        reviewCount: 210,
        imageUrl: "https://placehold.co/400x300/ADD8E6/FFFFFF?text=Baekkob",
    },
    {
        id: "r11",
        name: "몽슈슈 상암",
        category: "카페/디저트",
        address: "서울 마포구 월드컵북로",
        rating: 4.5,
        reviewCount: 110,
        imageUrl: "https://placehold.co/400x300/FF69B4/FFFFFF?text=MonChouchou",
    },
    {
        id: "r12",
        name: "서룡",
        category: "중식",
        address: "서울 마포구 월드컵북로",
        rating: 4.3,
        reviewCount: 400,
        imageUrl: "https://placehold.co/400x300/DC143C/FFFFFF?text=Seoryong",
    },
    {
        id: "r13",
        name: "봉피양 상암",
        category: "한식/평양냉면",
        address: "서울 마포구 월드컵북로",
        rating: 4.2,
        reviewCount: 300,
        imageUrl: "https://placehold.co/400x300/C0C0C0/FFFFFF?text=Bongpiyang",
    },
    {
        id: "r14",
        name: "스시토와",
        category: "일식/스시",
        address: "서울 마포구 매봉산로",
        rating: 4.6,
        reviewCount: 80,
        imageUrl: "https://placehold.co/400x300/FA8072/FFFFFF?text=SushiTowa",
    },
    {
        id: "r15",
        name: "다이닝 야경",
        category: "일식/이자카야",
        address: "서울 마포구 상암동",
        rating: 4.1,
        reviewCount: 60,
        imageUrl: "https://placehold.co/400x300/2F4F4F/FFFFFF?text=Yakyung",
    },
    {
        id: "r16",
        name: "마포 만두",
        category: "분식",
        address: "서울 마포구 월드컵북로",
        rating: 4.0,
        reviewCount: 500,
        imageUrl: "https://placehold.co/400x300/FFA07A/FFFFFF?text=MapoMandu",
    },
    {
        id: "r17",
        name: "김영섭 초밥",
        category: "일식",
        address: "서울 마포구 월드컵북로",
        rating: 4.7,
        reviewCount: 450,
        imageUrl: "https://placehold.co/400x300/FF4500/FFFFFF?text=KYS_Sushi",
    },
    {
        id: "r18",
        name: "트라토리아 몰토",
        category: "양식/파스타",
        address: "서울 마포구 월드컵북로",
        rating: 4.8,
        reviewCount: 220,
        imageUrl: "https://placehold.co/400x300/800000/FFFFFF?text=Molto",
    },
    {
        id: "r19",
        name: "오 오후 5시",
        category: "한식/퓨전",
        address: "서울 마포구 상암동",
        rating: 4.3,
        reviewCount: 130,
        imageUrl: "https://placehold.co/400x300/808000/FFFFFF?text=5PM",
    },
    {
        id: "r20",
        name: "청춘소고기",
        category: "고기",
        address: "서울 마포구 상암동",
        rating: 4.4,
        reviewCount: 90,
        imageUrl: "https://placehold.co/400x300/B22222/FFFFFF?text=Beef",
    },
    {
        id: "r21",
        name: "상암일미",
        category: "한식",
        address: "서울 마포구 상암동",
        rating: 4.2,
        reviewCount: 70,
        imageUrl: "https://placehold.co/400x300/D2691E/FFFFFF?text=Ilmi",
    },
    {
        id: "r22",
        name: "인칸토 키친",
        category: "양식/뷔페",
        address: "서울 마포구 매봉산로",
        rating: 4.1,
        reviewCount: 150,
        imageUrl: "https://placehold.co/400x300/9370DB/FFFFFF?text=Incanto",
    },
    {
        id: "r23",
        name: "닥터로빈 상암",
        category: "양식/파스타",
        address: "서울 마포구 매봉산로 DDMC",
        rating: 4.5,
        reviewCount: 300,
        imageUrl: "https://placehold.co/400x300/2E8B57/FFFFFF?text=DrRobbin",
    },
    {
        id: "r24",
        name: "폴바셋 상암",
        category: "카페/간단식",
        address: "서울 마포구 매봉산로",
        rating: 4.6,
        reviewCount: 600,
        imageUrl: "https://placehold.co/400x300/000000/FFFFFF?text=PaulBassett",
    },
    {
        id: "r25",
        name: "바스버거 상암",
        category: "버거",
        address: "서울 마포구 월드컵북로",
        rating: 4.5,
        reviewCount: 400,
        imageUrl: "https://placehold.co/400x300/FF8C00/FFFFFF?text=BasBurger",
    },
    {
        id: "r26",
        name: "쿠마",
        category: "일식/돈까스",
        address: "서울 마포구 상암동",
        rating: 4.4,
        reviewCount: 120,
        imageUrl: "https://placehold.co/400x300/8B4513/FFFFFF?text=Kuma",
    },
    {
        id: "r27",
        name: "무스 쿠스",
        category: "뷔페",
        address: "서울 마포구 매봉산로",
        rating: 4.0,
        reviewCount: 500,
        imageUrl: "https://placehold.co/400x300/4169E1/FFFFFF?text=Muscus",
    },
    {
        id: "r28",
        name: "한상 가득",
        category: "한식",
        address: "서울 마포구 상암동",
        rating: 4.2,
        reviewCount: 80,
        imageUrl: "https://placehold.co/400x300/DAA520/FFFFFF?text=Hansang",
    },
    {
        id: "r29",
        name: "교대 이층집 상암",
        category: "고기",
        address: "서울 마포구 상암동",
        rating: 4.5,
        reviewCount: 250,
        imageUrl: "https://placehold.co/400x300/006400/FFFFFF?text=LeeCheung",
    },
    {
        id: "r30",
        name: "창고43 상암",
        category: "고기/소고기",
        address: "서울 마포구 매봉산로",
        rating: 4.6,
        reviewCount: 180,
        imageUrl: "https://placehold.co/400x300/191970/FFFFFF?text=Changgo",
    },
    {
        id: "r31",
        name: "버거앤프라이즈",
        category: "버거",
        address: "서울 마포구 상암동",
        rating: 4.1,
        reviewCount: 90,
        imageUrl: "https://placehold.co/400x300/FFDAB9/FFFFFF?text=BurgerFries",
    },
    {
        id: "r32",
        name: "에그드랍 상암",
        category: "샌드위치",
        address: "서울 마포구 월드컵북로",
        rating: 4.3,
        reviewCount: 300,
        imageUrl: "https://placehold.co/400x300/FFFFE0/FFFFFF?text=EggDrop",
    }
];
